services:
  jwo-business-service:
    container_name: jwo-business-service
    image: haphihung55/jwo-business-service
    build: .
    ports:
      - ${SERVICE_PORT:-5000}:${SERVICE_PORT:-5000}
    environment:
      - SERVICE_PORT=${SERVICE_PORT:-5000}
      - DB_URL=postgresql://${DB_USER}:${DB_PASSWORD}@jwo-business-db:${DB_PORT}/${DB_NAME}?schema=public
    depends_on:
      - jwo-business-db

  jwo-business-db:
    container_name: jwo-business-db
    image: postgres:16
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}
    environment:
      - PGPORT=${DB_PORT:-5432}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    name: ${VOLUME_NAME:-jwo-business-db-data}
